//
// Created by Administrateur on 27/11/2021.
//

#ifndef C0DETRACKER_GLOBAL_INSTRUMENTS_HPP
#define C0DETRACKER_GLOBAL_INSTRUMENTS_HPP
#include "../../include/c0de_tracker.hpp"

const uint_fast8_t GLOBAL_NUMBER_OF_INSTRUMENTS = 16;
enum GLOBAL_INSTRUMENTS_NAMES {KICK, SNARE, HITHAT, CRASH, WOOD, AMBIANT_SINE, AMBIANT_SINE2, DEEP_BASS, SHARP_BASS, AMBIANT_SQU50,
    AMBIANT_SINE3, SQUARE_WAVE, LG,
    HOVER_FX, TRANS_FX0, GAME_OVER_FX0};
enum GLOBAL_CHANNEL_NAMES {CHAN0, CHAN1,CHAN2, CHAN3, CHAN4, CHAN5, CHAN6};


extern C0deTracker::Instrument_Data GLOBAL_INSTRUMENTS_BANK[GLOBAL_NUMBER_OF_INSTRUMENTS];
extern bool IS_GLOBAL_INSTRUMENTS_BANK_INITIALISED;
void initGlobalInstruments();

#endif //C0DETRACKER_GLOBAL_INSTRUMENTS_HPP
